### ISSUE TITLE
Sends caps before stream-start warning

### ISSUE THREAD

**Issue by ndufresne** [sugarlabs/gst-plugins-espeak#1]
There is a bug in this element that cause a event miss-ordering bug. The problem is here:

 https://github.com/sugarlabs/gst-plugins-espeak/blob/master/src/gstespeak.c#L280

You bypass the base class, should in theory works if you simply replace with:

  gst_base_src_set_caps (self_, self->caps);

**Comment by quozl** [comment]
Thanks, I'll give that a try.

**Comment by quozl** [comment]
I've tested this change on Ubuntu 18.04 beta and the Speak activity without seeing any new issues or regressions, so I'll commit it soon.

**Comment by ndufresne** [comment]
Great, thanks !

**Comment by quozl** [comment]
https://github.com/sugarlabs/gst-plugins-espeak/commit/125c6c0cbe822b948eb549820a04ae52b6ec1afe
