### ISSUE TITLE
Doesn't build with espeak-ng

### ISSUE THREAD

**Issue by nullr0ute** [sugarlabs/gst-plugins-espeak#4]
it looks like with 00ac552 that espeak-ng support has been added but it seems that the configure check needs to be updated to find espeak-ng as it fails if you try to build against it (tried both 1.49 and 1.50):

<pre>
checking for GST... yes
checking for GST_AUDIO... yes
checking for espeak_Initialize in -lespeak... no
configure: error: 
</pre>

**Comment by quozl** [comment]
Thanks.  On Debian and Ubuntu libespeak.so is a symbolic link to libespeak-ng.so.  Please review https://github.com/sugarlabs/gst-plugins-espeak/pull/5.

**Comment by nullr0ute** [comment]
Gets us further along, doesn't update the include paths though it seems:

<pre>
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/orc-0.4 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c gstespeak.c  -fPIC -DPIC -o .libs/libgstespeak_la-gstespeak.o
espeak.c:22:10: fatal error: espeak/speak_lib.h: No such file or directory
   22 | #include <espeak/speak_lib.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:462: libgstespeak_la-espeak.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
gstespeak.c: In function 'gst_espeak_class_init':
gstespeak.c:121:21: warning: 'g_value_array_get_type' is deprecated: Use 'GArray' instead [-Wdeprecated-declarations]
  121 |                     "List of voices", G_TYPE_VALUE_ARRAY,
      |                     ^~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib-object.h:34,
                 from /usr/include/gstreamer-1.0/gst/gstenumtypes.h:7,
                 from /usr/include/gstreamer-1.0/gst/gst.h:31,
                 from gstespeak.c:35:
/usr/include/glib-2.0/gobject/gvaluearray.h:60:17: note: declared here
   60 | GType           g_value_array_get_type       (void) G_GNUC_CONST;
      |                 ^~~~~~~~~~~~~~~~~~~~~~
gstespeak.c:121:13: warning: Deprecated pre-processor symbol, replace with 
  121 |                     "List of voices", G_TYPE_VALUE_ARRAY,
      |             ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
gstespeak.c: In function 'gst_espeak_finalize':
gstespeak.c:175:5: warning: 'g_value_array_free' is deprecated: Use 'GArray' instead [-Wdeprecated-declarations]
  175 |     g_value_array_free (self->voices);
      |     ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib-object.h:34,
                 from /usr/include/gstreamer-1.0/gst/gstenumtypes.h:7,
                 from /usr/include/gstreamer-1.0/gst/gst.h:31,
                 from gstespeak.c:35:
/usr/include/glib-2.0/gobject/gvaluearray.h:70:7: note: declared here
   70 | void  g_value_array_free      (GValueArray *value_array);
      |       ^~~~~~~~~~~~~~~~~~
make[2]: Leaving directory '/builddir/build/BUILD/gst-plugins-espeak-0.5.0/src'
make[1]: *** [Makefile:405: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/gst-plugins-espeak-0.5.0'
make: *** [Makefile:337: all] Error 2
</pre>

A "sed -i s#espeak/speak_lib.h#espeak-ng/speak_lib.h# src/espeak.c" worked around it but I'm sure there's a more elegant option.

With the above that patch set looks good to me.

**Comment by quozl** [comment]
Thanks for testing.
